//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ATMEntities : DbContext
    {
        public ATMEntities()
            : base("name=ATMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
    
        public virtual ObjectResult<SP_getAllPeople_Result> SP_getAllPeople()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_getAllPeople_Result>("SP_getAllPeople");
        }
    
        public virtual ObjectResult<sp_getAllRol_Result> sp_getAllRol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getAllRol_Result>("sp_getAllRol");
        }
    }
}
